[package]
name = "rs-rest-crud"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
mongodb = "3.3.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }

[profile.release]
codegen-units = 1
